<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ecommerceApiDemo.Domain\ecommerceApiDemo.Domain.csproj" />
    <ProjectReference Include="..\ecommerceApiDemo.Application\ecommerceApiDemo.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
